# Generated by Django 5.0.7 on 2024-11-12 15:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KategoriJasa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nama_kategori", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SubkategoriJasa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nama_subkategori", models.CharField(max_length=255)),
                ("deskripsi", models.TextField()),
                (
                    "kategori_jasa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subkategori_jasa.kategorijasa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SesiLayanan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sesi", models.IntegerField()),
                ("harga", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "subkategori",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subkategori_jasa.subkategorijasa",
                    ),
                ),
            ],
            options={
                "unique_together": {("subkategori", "sesi")},
            },
        ),
    ]
