# Generated by Django 5.0.7 on 2024-11-17 12:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subkategori_jasa", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subkategorijasa",
            name="kategori_jasa",
        ),
        migrations.AlterUniqueTogether(
            name="sesilayanan",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="sesilayanan",
            name="subkategori",
        ),
        migrations.DeleteModel(
            name="KategoriJasa",
        ),
        migrations.DeleteModel(
            name="SesiLayanan",
        ),
        migrations.DeleteModel(
            name="SubkategoriJasa",
        ),
    ]
